export { default as icon1 } from "./Icon1.png";
export { default as icon2 } from "./Icon2.png";
export { default as icon3 } from "./Icon3.png";
export { default as icon4 } from "./Icon4.png";
export { default as icon5 } from "./Icon5.png";
export { default as icon6 } from "./Icon6.png";
export { default as bug } from "./bug.svg";
export { default as cloud } from "./cloud.svg";
export { default as shield } from "./shield.svg";
